name: "🚀 Feature request"
description: "Suggest an idea for this project"
labels: ["enhancement"]
assignees: "Lurkars"
body:
  - type: textarea
    id: feagure-description
    attributes:
      label: Describe the feature
      description: |
        A clear and concise description of what the feature request is.
    validations:
      required: true
